"""Fill the measured-results block of docs/research/16_pipe_clogging.md from eval/clog/*.json (no typed numbers).

Replaces the text between <!-- clog:results:start --> and <!-- clog:results:end --> in the doc.

    python scripts/clog_doc_tables.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cascade.building.clog import report as RPT  # noqa: E402

EVAL = ROOT / "eval" / "clog"
DOC = ROOT / "docs" / "research" / "16_pipe_clogging.md"
START, END = "<!-- clog:results:start -->", "<!-- clog:results:end -->"
SEV = {"0": "clean", "1": "mild", "2": "moderate", "3": "severe"}


def load(name: str) -> dict:
    return json.loads((EVAL / name).read_text(encoding="utf-8"))


def pct(x) -> str:
    return "" if x is None else f"{100 * x:.1f}%"


def ci(c) -> str:
    return f"{100 * c[0]:.1f}-{100 * c[1]:.1f}%"


def table(header, rows) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(x) for x in r) + " |" for r in rows]
    return "\n".join(out)


def build() -> str:
    riser, drain, bell = load("riser_metrics.json"), load("drain_test.json"), load("bellinge_case.json")
    sched, man, sim = load("schedule.json"), load("data_manifest.json"), load("sim_check.json")
    base = riser["variants"]["base"]
    det = base["detectors"]
    d = riser["design"]
    parts = ["_Generated by `scripts/clog_doc_tables.py` from `eval/clog/*.json`; do not edit by hand._"]

    parts.append("### Inputs (REAL) and their hashes\n")
    parts.append(table(["dataset", "kind", "licence", "bytes", "sha256 (first 16)"],
                       [[f["dataset"], f["kind"], f["licence"], f["bytes"], (f["sha256"] or "")[:16]]
                        for f in man["files"]]))
    hs = man.get("hsb_stats")
    if hs:
        parts.append(f"\nHSB properties computed by `fetch_clog_data.py`: {hs['rows']} rows, {hs['n_apartments']} "
                     f"apartments, total `value` {hs['total_value_m3']} (m3), share of volume with no apartment "
                     f"(shared spaces, dropped) {pct(hs['share_of_volume_without_apartment'])}, UTC span "
                     f"{hs['first_timestamp_utc']} to {hs['last_timestamp_utc']}.")

    parts.append("\n### Riser simulation (SIMULATED riser, INJECTED clogs, REAL demand)\n")
    parts.append(f"{sim['n_sims']} simulated weeks; engines {sim['engine_counts']}; weeks with non-converged steps "
                 f"{sim['sims_with_nonconverged_steps']}; median {sim['median_seconds_per_week']} s per week; wall "
                 f"{sim['wall_seconds']} s. HSB good weeks: train pool {sim['hsb_good_weeks']['train_pool']}, test pool "
                 f"{sim['hsb_good_weeks']['test_pool']}. Commissioning weeks {sim['commissioning_weeks']}. Train "
                 f"weeks: {', '.join(sim['weeks']['train'])}. Test weeks: {', '.join(sim['weeks']['test'])}.\n")
    parts.append("Engine cross-check (EPANET vs WNTRSimulator, max absolute pressure difference over all sensors and "
                 "steps):\n")
    parts.append(table(["clog pipe", "K", "EPANET s", "WNTRSimulator s", "max abs diff (m)"],
                       [[c["clog_pipe"], c["K"], c["epanet_s"], c["wntrsim_s"], c["max_abs_diff_m"]]
                        for c in sim["engine_check"]["cases"]]))

    parts.append(f"\n### Held-out test: alarm rate per night by true state\n\n{base['label']}: {base['n_scenarios']} "
                 f"scenarios ({base['n_nights']} nights); scenarios per state "
                 f"{ {SEV[k]: v for k, v in base['scenarios_by_severity'].items()} }. Train: "
                 f"{d['train']['n_scenarios']} scenarios ({d['train']['n_nights']} nights). Threshold: "
                 f"{d['threshold']}. CI: {d['ci']}. Severity bands (K): {d['k_bands']}.\n")
    rows = []
    for k, r in det.items():
        a = r["alarm"]
        rows.append([r["label"]] + [f"{pct(a[s]['rate'])} ({ci(a[s]['ci95'])})" for s in ("0", "1", "2", "3")])
    parts.append(table(["detector", "clean = false alarms", "mild", "moderate", "severe"], rows))

    parts.append("\n### Held-out test: grading and locating\n")
    rows = []
    for k, r in det.items():
        sv, lo = r.get("severity"), r.get("localisation")
        rows.append([r["label"],
                     f"{sv['macro_f1']:.3f} ({sv['macro_f1_ci95'][0]:.3f}-{sv['macro_f1_ci95'][1]:.3f})" if sv else "-",
                     f"{sv['qwk']:.3f}" if sv else "-",
                     f"{pct(lo['2']['accuracy'])} ({ci(lo['2']['ci95'])})" if lo else "-",
                     f"{pct(lo['3']['accuracy'])} ({ci(lo['3']['ci95'])})" if lo else "-",
                     pct(r["alarm"]["0"]["persistent_2of3"]), pct(r["alarm"]["2"]["persistent_2of3"])])
    bl = riser["baselines_macro_f1"]
    names = bl["class_names"]
    rows.append([f"Baseline: always '{bl['majority_class_name']}' (training majority)",
                 f"{bl['majority_macro_f1']:.3f}", "-", f"chance {pct(1 / len(d['locations']))}", "-", "-", "-"])
    rows += [[f"Baseline: always '{names[int(k)]}'", f"{v:.3f}", "-", "-", "-", "-", "-"]
             for k, v in bl["constant_macro_f1"].items() if int(k) != bl["majority_class"]]
    sr = bl["stratified_random"]
    rows.append(["Baseline: random grade at training class frequencies",
                 f"{sr['mean']:.3f} ({sr['range95'][0]:.3f}-{sr['range95'][1]:.3f} over {sr['n_draws']} draws)", "-",
                 "-", "-", "-", "-"])
    parts.append(table(["detector", "macro-F1 (95% CI)", "QWK", "locate moderate", "locate severe",
                        "persistent alarm, clean weeks", "persistent alarm, moderate weeks"], rows))
    parts.append(f"\nMacro-F1 is scored on test nights; training class frequencies {[round(x, 3) for x in bl['train_class_freq']]} "
                 f"({', '.join(names)}), so the training majority class is '{bl['majority_class_name']}'.")

    parts.append("\n### Out-of-distribution stress tests (same thresholds)\n")
    rows = []
    for v, vr in riser["variants"].items():
        for k in ("act4_z", "act4_hgb", "act25_z", "pas_z", "pas_hgb", "bms"):
            a = vr["detectors"][k]["alarm"]
            rows.append([vr["label"], vr["detectors"][k]["label"], f"{pct(a['0']['rate'])} ({ci(a['0']['ci95'])})",
                         pct(a["2"]["rate"]), pct(a["3"]["rate"])])
    parts.append(table(["condition", "detector", "false alarms (95% CI)", "moderate", "severe"], rows))

    parts.append("\n### Commissioning sensitivity (test building reference redrawn with new noise)\n")
    rows = [[det[k]["label"], SEV[s], pct(v["median"]), pct(v["min"]), pct(v["max"]), v["n_draws"]]
            for k, dd in riser["commissioning_sensitivity"].items() for s, v in dd.items()]
    parts.append(table(["detector", "true state", "median", "min", "max", "draws"], rows))

    parts.append("\n### Moderate-or-severe clogs flagged, by location (held-out test)\n")
    rows = [[r["name"]] + [pct(riser["moderate_plus_by_location"][k][i]["rate"]) for k in
                           ("act4_z", "act4_hgb", "act25_hgb")] + [r["n_scenarios"]]
            for i, r in enumerate(riser["moderate_plus_by_location"]["act4_z"])]
    parts.append(table(["location", det["act4_z"]["label"], det["act4_hgb"]["label"], det["act25_hgb"]["label"],
                        "scenarios"], rows))

    dm = drain["model"]
    parts.append(f"\n### Drain-down test (SIMULATED drain, INJECTED orifice clogs)\n\nTest {dm['test']['lps']} L/s for "
                 f"{dm['test']['seconds']} s; level noise sd {dm['level_noise']['sd']} m, logging step "
                 f"{dm['level_noise']['step']} m (assumptions). Evaluation draws are level-noise redraws over "
                 f"{len(dm['base_flows_lps'])} deterministic SWMM runs per opening (base flows {dm['base_flows_lps']} "
                 f"L/s). Commissioning drain-down "
                 f"{drain['commissioning']['drain_down_median_s']} s. Thresholds (p95 of clean calibration draws): "
                 f"{drain['thresholds']}.\n")
    parts.append(table(["opening", "drain-down median (s)", "never drained (share)", "flagged by drain-down",
                        "flagged by peak level", "graded urgent", "draws"],
                       [[r["opening"], r["drain_down_median_s"], pct(r["censored_share"]),
                         pct(r["detect_rate_drain_down"]), pct(r["detect_rate_peak"]), pct(r["share_urgent"]),
                         r["n_draws"]] for r in drain["rows"]]))

    h = bell["headline"]
    parts.append(f"\n### Bellinge July 2020 blockage (REAL, one event)\n\n{bell['label']}. Train "
                 f"{bell['periods']['train']}, held-out {bell['periods']['test']} ({bell['test_months']:.2f} months), "
                 f"documented event {bell['periods']['event']}. Onset {bell['onset']['time']} "
                 f"({bell['onset']['definition']}). Normal model: {bell['normal_model']['type']}, out-of-fold training "
                 f"MAE {bell['normal_model']['mae_train_oof_m']:.4f} m, held-out MAE (event excluded) "
                 f"{bell['normal_model']['mae_test_excl_event_m']:.4f} m; threshold basis: "
                 f"{bell['normal_model']['threshold_basis']}.\n")
    rows = [["paired rule", h["paired"]["first_alarm"], h["paired"]["delay_min_from_onset"],
             h["paired"]["other_test_episodes"], h["paired"]["train_episodes"]],
            ["upstream residual only", h["residual_only"]["first_alarm"], h["residual_only"]["delay_min_from_onset"],
             h["residual_only"]["other_test_episodes"], h["residual_only"]["train_episodes"]],
            ["downstream drop only", h["downstream_drop_only"]["first_alarm"],
             h["downstream_drop_only"]["delay_min_from_onset"], h["downstream_drop_only"]["other_test_episodes"],
             h["downstream_drop_only"]["train_episodes"]]]
    rows += [[f"fixed level > {f['threshold_m']:.3f} m ({f['label']})", f["first_alarm"], f["delay_min_from_onset"],
              f["other_test_episodes"], f["train_episodes"]] for f in h["fixed_levels"]]
    srcs = [h["paired"], h["residual_only"], h["downstream_drop_only"]] + h["fixed_levels"]
    for r, src in zip(rows, srcs):
        r.append(f"{src['pre_onset_episodes']} (first {src['pre_onset_first']}), not attributable"
                 if src.get("pre_onset_episodes") else "0")
    parts.append(table(["detector", "first attributable alarm (local)", "minutes after onset",
                        "other held-out episodes", "training-month episodes", "episodes in event window before onset"],
                       rows))
    parts.append(f"\nAn episode inside the documented dates counts as a detection only if it starts no more than "
                 f"{h['paired']['pre_onset_margin_min']} min before the visible onset; earlier ones are added to the "
                 f"other held-out episodes.")
    sw = bell["sweep"]["paired_summary"]
    parts.append(f"\nParameter sweep of the paired rule: {sw['n_detected']} of {sw['n_configs']} settings detected "
                 f"the event; first alarms {sw['first_alarm_range'][0]} to {sw['first_alarm_range'][1]}; other held-out "
                 f"episodes {sw['other_test_episodes_range'][0]}-{sw['other_test_episodes_range'][1]}.")

    parts.append(f"\n### Proposed check calendar (as of {sched['as_of']}; {sched['register_label']})\n")
    parts.append(table(["next check", "status", "asset", "why", "who", "rules", "input"],
                       [[r["next_check"], r["status"], f"{r['asset_id']}: {r['asset']}", r["reason"],
                         r["performed_by"], ", ".join(r["rule_keys"]), r["input_provenance"]]
                        for r in sched["rows"]]))

    parts.append("\n### Conclusions as computed for the page (`report.conclusions`)\n")
    parts += [f"- **{c['topic']}** [{c['label']}] {c['text']}" for c in RPT.conclusions(riser, drain, bell, sched)]
    return "\n".join(parts) + "\n"


def main() -> int:
    text = DOC.read_text(encoding="utf-8")
    a, b = text.index(START) + len(START), text.index(END)
    DOC.write_text(text[:a] + "\n" + build() + text[b:], encoding="utf-8")
    print(f"updated {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
