"""Step 3 of the numeric backtest (runtime env): merge every forecast parquet and score them against seasonal naive.

Inputs (all generated by our scripts): eval/numeric/forecasts_baselines_hgb.parquet, forecasts_chronos_2.parquet,
forecasts_chronos_bolt_small.parquet (+ .provenance.json), backtest_setup.json, bdg2_selected.parquet.
Outputs: eval/numeric/backtest_bdg2.json (the numbers the page shows) and eval/numeric/bdg2_indicators.parquet
(robust-z anomaly indicator on the REAL test-window series; an indicator with no ground truth, so no accuracy claim).

Run: C:\\Users\\HP\\miniconda3\\envs\\origin_hack\\python.exe scripts/numeric_evaluate.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from cascade.numeric.agent import HF_MODELS, THRESHOLD_SOURCE, _anomaly_threshold  # noqa: E402
from cascade.numeric.backtest import score  # noqa: E402
from cascade.numeric.base import EVAL_DIR, git_head, utc_now  # noqa: E402
from cascade.numeric.baselines import MAD_TO_SD, RobustZ  # noqa: E402

LABELS = {
    "snaive168": ("Seasonal naive (same hour last week)", "baseline"),
    "naive24": ("Naive (same hour yesterday)", "baseline"),
    "hgb": ("scikit-learn HGB + split-conformal 80% band (trained to 30 Sep, band calibrated on Oct)", "sklearn"),
    "hgb_oct": ("scikit-learn HGB refit to 31 Oct (point forecast only, no band)", "sklearn"),
    "chronos_2": ("Chronos-2 (amazon/chronos-2), zero-shot", "hugging-face"),
    "chronos_bolt_small": ("Chronos-Bolt-small (amazon/chronos-bolt-small), zero-shot", "hugging-face"),
}
OVERLAP = {
    "chronos_2": ("Test sites exclude every BDG2 site in Salesforce/GiftEvalPretrain. The amazon/chronos-2 card metadata "
                  "lists GiftEvalPretrain among its datasets; the Chronos-2 paper's Table 6 lists no BDG-2 subset "
                  "(research verifier, 2026-09-26). The same card metadata also lists autogluon/chronos_datasets, "
                  "which was not checked for BDG2 sites. Remaining overlap with the test sites: not known."),
    "chronos_bolt_small": ("Training corpus not named on the card ('nearly 100 billion time series observations'). "
                           "GIFT-Eval-Pretrain sites are excluded from the test pool; other overlap: possible, unverified."),
}


def main() -> None:
    setup = json.loads((EVAL_DIR / "backtest_setup.json").read_text(encoding="utf-8"))
    fr = pd.read_parquet(EVAL_DIR / "forecasts_baselines_hgb.parquet")
    fr["origin"] = pd.to_datetime(fr["origin"])
    fr["ts"] = pd.to_datetime(fr["ts"])
    provs = {}
    for name, spec in HF_MODELS.items():
        pq = EVAL_DIR / f"forecasts_{spec.tag}.parquet"
        pv = EVAL_DIR / f"forecasts_{spec.tag}.provenance.json"
        if not (pq.exists() and pv.exists()):
            print("missing", pq.name, "- run scripts/numeric_chronos_precompute.py in the cerebro_ml env")
            continue
        meta = json.loads(pv.read_text(encoding="utf-8"))
        if meta.get("revision") != spec.revision:
            print("revision mismatch for", spec.model_id, "- skipped")
            continue
        c = pd.read_parquet(pq)
        c["ts"] = pd.to_datetime(c["ts"])
        c = c.rename(columns={"q10": f"{spec.tag}_q10", "q50": f"{spec.tag}_q50", "q90": f"{spec.tag}_q90"})
        fr = fr.merge(c[["meter", "ts", f"{spec.tag}_q10", f"{spec.tag}_q50", f"{spec.tag}_q90"]],
                      on=["meter", "ts"], how="left")
        provs[spec.tag] = meta

    scales = setup["mase_scale_kWh"]
    primary = "chronos_2" if "chronos_2_q50" in fr else None
    res = score(fr, scales, baseline="snaive168", primary=primary, site_of=setup["selection"]["site_of"])
    for m, d in res["models"].items():
        d["label"], d["kind"] = LABELS.get(m, (m, "other"))
        if m in OVERLAP:
            d["pretraining_overlap"] = OVERLAP[m]
    # the same scoring without the point-only refit, so every row shares the exact scored hours with the band models
    res["n_origins"] = int(fr.origin.nunique())
    res["horizon_h"] = int(setup["config"]["horizon"])

    # anomaly indicator on the REAL test window (robust z; K and 1.4826 x MAD scale as the building layer)
    sel = pd.read_parquet(EVAL_DIR / "bdg2_selected.parquet")
    sel.index = pd.to_datetime(sel.index)
    k = _anomaly_threshold()
    t0 = pd.Timestamp(setup["config"]["test_start"])
    t1 = fr.ts.max()
    ind, per_meter_flags = [], {}
    for b in setup["selection"]["chosen"]:
        s = RobustZ(threshold=k).scores(sel[b])
        w = (s.index >= t0) & (s.index <= t1)
        d = pd.DataFrame({"meter": b, "ts": s.index[w], "y": sel[b].reindex(s.index[w]).to_numpy(),
                          "robust_z": s[w].to_numpy()})
        d["flag"] = d.robust_z >= k
        ind.append(d)
        per_meter_flags[b] = int(d.flag.sum())
    ind = pd.concat(ind, ignore_index=True)
    scored = ind.robust_z.notna()  # hours with a score; the share is taken over these only
    ind.to_parquet(EVAL_DIR / "bdg2_indicators.parquet", index=False)
    band_exits = {}
    for tag in ("hgb", "chronos_2", "chronos_bolt_small"):
        if f"{tag}_q10" in fr:
            ok = fr[["y", f"{tag}_q10", f"{tag}_q90"]].notna().all(axis=1)
            f = fr[ok]
            band_exits[tag] = float(((f.y < f[f"{tag}_q10"]) | (f.y > f[f"{tag}_q90"])).mean())
    out = {"created_utc": utc_now(), "code_git_sha": git_head(), "config": setup["config"],
           "selection": setup["selection"], "selection_diagnostics": setup.get("selection_diagnostics"),
           "data": setup["data"], "imputation": setup["imputation"],
           "mase_scale_kWh": scales, "hgb_params": setup["hgb_params"],
           "hgb_fit_seconds_total": round(float(sum(setup["hgb_fit_seconds_per_meter"].values())), 1),
           "hf_provenance": provs, **res,
           "indicators": {"method": "robust_z", "threshold": k,
                          "threshold_unit": f"{MAD_TO_SD} x MAD (sd-equivalents)",
                          "threshold_source": THRESHOLD_SOURCE,
                          "n_hours": int(scored.sum()), "n_flagged": int(ind.flag[scored].sum()),
                          "flag_share": float(ind.flag[scored].mean()), "flags_per_meter": per_meter_flags,
                          "sensitivity_raw_mads": {
                              "note": "same K in raw MADs (robust_z x 1.4826 >= K); NOT the building layer's scale",
                              "n_flagged": int((ind.robust_z[scored] * MAD_TO_SD >= k).sum()),
                              "flag_share": float((ind.robust_z[scored] * MAD_TO_SD >= k).mean())},
                          "band_exit_share": band_exits,
                          "note": "REAL series, no anomaly labels: these are indicators for a person to review, "
                                  "not measured detections. An 80% band is expected to be exited about 20% of hours."}}
    (EVAL_DIR / "backtest_bdg2.json").write_text(json.dumps(out, indent=1), encoding="utf-8")
    tab = pd.DataFrame({m: {k2: d.get(k2) for k2 in ("WAPE_pct", "MASE_mean_over_meters", "CVRMSE_pct", "NMBE_pct",
                                                    "coverage_80", "meters_better_than_baseline")}
                        for m, d in res["models"].items()}).T
    print(tab.to_string())
    print("scored hours", res["n_scored_hours"], "dropped", res["n_dropped_hours"], "band exits", band_exits,
          "flags", int(ind.flag.sum()))


if __name__ == "__main__":
    main()
